---
galaxy_info:
  author: Fabian Koehler
  description: Install and configure libvirt and KVM/QEMU virtualization on Archlinux.
  company: ""
  license: MIT
  min_ansible_version: "2.9"
dependencies: []
