- name: disable default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: remove default config
  file:
    path: /etc/nginx/sites-available/default
    state: absent
  notify: restart nginx
  become: yes

- name: install nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
