- name: install realtime privileges
  pacman:
    name: realtime-privileges
    state: present
  become: yes

- name: install jack2
  pacman:
    name: jack2
    state: present
    force: yes
  become: yes

- name: install Cadence GUI for jack
  pacman:
    name: cadence
    state: present
  become: yes

- name: setup GStreamer compatibility
  pacman:
    name: gst-plugins-good
    state: present
  become: yes

- name: disable pulseaudio autospawn
  replace:
    path: /etc/pulse/client.conf
    regexp: '^\s*autospawn\s*=\s*yes\s*$'
    replace: "autospawn = no"
  become: yes

- name: install alsa-plugins
  pacman:
    name: alsa-plugins
    state: present
  become: yes

- name: configure ALSA
  copy:
    src: asound.conf
    dest: /etc/asound.conf
  become: yes

- name: install pulseaudio jack
  pacman:
    name: pulseaudio-jack
    state: present
  become: yes
