- name: Set timezone
  timezone:
    name: Europe/Berlin
  become: yes

- name: Install NTP
  pacman:
    name: ntp
    state: present
  become: yes

- name: Enable NTP
  service:
    name: ntpd.service
    state: started
    enabled: yes
  become: yes
