# Copyright © 2015 Fabian Köhler <fkoehler1024@googlemail.com>
- name: install yajl
  when: ansible_distribution == 'Archlinux'
  pacman: name=yajl state=installed

- name: build package-query
  when: ansible_distribution == 'Archlinux'
  shell: wget "https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz" && tar xf package-query.tar.gz && cd package-query && makepkg -f
  args:
    creates: /usr/bin/package-query
    chdir: /tmp
  become: yes
  become_user: ansible

- name: install package-query
  shell: pacman --noconfirm -U *.pkg.tar.xz
  args:
    creates: /usr/bin/package-query
    chdir: /tmp/package-query

- name: build yaourt
  when: ansible_distribution == 'Archlinux'
  shell: wget "https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz" && tar xf yaourt.tar.gz && cd yaourt && makepkg -f
  args:
    creates: /usr/bin/yaourt
    chdir: /tmp
  become: yes
  become_user: ansible

- name: install yaourt
  shell: pacman --noconfirm -U *.pkg.tar.xz
  args:
    creates: /usr/bin/yaourt
    chdir: /tmp/yaourt
