- name: set ntp service name
  set_fact:
    ntp_service_name: ntpd

- name: install ntp
  pacman:
    name: ntp
    state: present
  become: yes
  notify:
    - restart ntpd

- name: copy ntp config
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
  become: yes
  notify:
    - restart ntpd

- name: start/enable ntpd
  service:
    name: "{{ ntp_service_name }}"
    enabled: yes
    state: started
  become: yes
