- name: install netdata
  pacman:
    name: netdata
    state: present
  become: yes
  when: ansible_distribution == "Archlinux"

- name: install netdata
  apt:
    name: netdata
    state: present
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: enable netdata
  service:
    name: netdata
    enabled: yes
    state: started
  become: yes
