- name: install packages
  ansible.builtin.package:
    name:
      - "{{ item }}"
  loop:
    - libvirt
    - ebtables
    - dnsmasq
    - bridge-utils
    - openbsd-netcat
    - qemu
    - qemu-arch-extra
    - samba
    - virt-install

- name: configure module loading
  ansible.builtin.template:
    src: modules-load.conf.j2
    dest: /etc/modules-load.d/kvm.conf

- name: configure module options
  ansible.builtin.template:
    src: modprobe.conf.j2
    dest: /etc/modprobe.d/kvm.conf

- name: load modules
  community.general.modprobe:
    name: "{{ item }}"
  loop:
    - kvm
    - "kvm_{{ kvm_provider }}"

- name: enable hugepages
  when: kvm_hugepages
  block:
    - name: create fstab entry for hugepages
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^\s*hugetlbfs\s+/dev/hugepages'
        line: "hugetlbfs /dev/hugepages hugetlbfs mode{{'='}}01770,gid{{'='}}kvm 0 0"
      register: hugepages_fstab

    - name: remount hugepages
      ansible.posix.mount:
        path: /dev/hugepages
        src: "hugetlbfs"
        fstype: "hugetlbfs"
        state: remounted
      when: hugepages_fstab.changed

    - name: mount hugepages
      ansible.posix.mount:
        path: /dev/hugepages
        src: "hugetlbfs"
        fstype: "hugetlbfs"
        state: mounted

- name: ensure that the libvirt group exists
  ansible.builtin.group:
    name: libvirt
    system: yes

- name: add users to the libvirt group
  ansible.builtin.user:
    name: "{{ item }}"
    append: yes
    groups:
      - libvirt
  loop: "{{ kvm_users }}"

- name: enable libvirt service
  ansible.builtin.systemd:
    name: libvirtd.service
    state: started
    enabled: yes
