- name: install haveged
  pacman:
    name: haveged
    state: present
  become: yes
  notify: restart haveged

- name: start/enable haveged
  service:
    name: haveged
    state: started
    enabled: yes
  become: yes
