http:
  routers:
    nextcloud:
      rule: "Host(`nextcloud.fkoehler.xyz`)"
      service: "nextcloud"
      entrypoints:
        - "https"
      tls:
        options: modern
    nextcloud_http:
      rule: "Host(`nextcloud.fkoehler.xyz`)"
      service: "nextcloud"
      entrypoints:
        - "http"
      middlewares:
        - "redirect-to-https"
    git:
      rule: "Host(`git.fkoehler.xyz`)"
      service: "gitea"
      entrypoints:
        - "https"
      tls:
        options: modern
      middlewares:
        - "hsts-headers"
    git_http:
      rule: "Host(`git.fkoehler.xyz`)"
      service: "gitea"
      entrypoints:
        - "http"
      middlewares:
        - "redirect-to-https"
        - "hsts-header"
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    hsts-header:
      headers:
        Strict-Transport-Security: "max-age=63072000"
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud:80/"
    gitea:
      loadBalancer:
        servers:
          - url: "http://gitea:3000/"
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/letsencrypt/live/fkoehler.xyz/fullchain.pem
        keyFile: /etc/letsencrypt/live/fkoehler.xyz/privkey.pem
  options:
    modern:
      minVersion: VersionTLS13
