repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier
  - repo: https://github.com/ansible/ansible-lint
    rev: master
    hooks:
      - id: ansible-lint
