- hosts: desktops
  connection: local
  become: yes
  vars:
    timezone: "Europe/Berlin"
  roles:
    - localtime
    - haveged
    - thunar
    - yay
    - openafs

    - docker
    - kvm
    - heimdall
