---
collections:
  - name: community.general
    version: "11.4.1"
  - name: community.crypto
    version: "3.0.5"
  - name: ansible.posix
    version: "2.1.0"
  - name: ansible.utils
    version: "6.0.0"
  - name: geerlingguy.mac
    version: "4.1.0"
