- hosts: webservers
  become: yes
  vars:
    timezone: "Europe/Berlin"
  roles:
    # - hardened_ssh_server
    # - localtime
    # - haveged
    # - docker
    # - vps_firewall
    - vps_containers
