- hosts: webservers
  become: yes
  vars:
    timezone: "Europe/Berlin"
  roles:
    - vps-kernel
    - firewall
    - hardened-ssh-server
    - localtime
    - haveged
    - docker
    - vps-containers
