- name: find reachable hosts
  hosts: workstations
  gather_facts: no
  tasks:
    - name: dummy command to check if host is online
      command: /bin/true # noqa no-changed-when
      register: result
      ignore_errors: yes
    - name: register reachable hosts
      group_by:
        key: reachable
      when: result is success

- hosts: reachable
  become: yes
  roles:
    - localtime
    - locale
    - haveged
    - kvm
    - cockpit
    - netdata
    - desktop
    - rootless_podman
    - cli
