- name: find reachable hosts
  hosts: workstations
  gather_facts: no
  tasks:
    - command: /bin/true
      register: result
      ignore_errors: yes
    - group_by: key=reachable
      when: result is success

- hosts: reachable
  become: yes
  roles:
    - localtime
    - haveged
    - yay
    - graphics_driver
    - desktop
