- name: flatpaks
  block:
    - name: install flatpak
      ansible.builtin.package:
        name: flatpak

    - name: add flathub repository
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    - name: install flatpaks
      community.general.flatpak:
        name: "{{ item }}"
        remote: flathub
      loop:
        - ch.protonmail.protonmail-bridge
        - com.bitwarden.desktop
        - com.discordapp.Discord
        - com.jgraph.drawio.desktop
        - com.skype.Client
        - im.riot.Riot
        - io.github.markummitchell.Engauge_Digitizer
        - org.signal.Signal
        - org.telegram.desktop
        - org.zotero.Zotero
        - us.zoom.Zoom
