- name: remove firefox
  pacman:
    name: firefox
    state: absent
  become: yes

- name: install firefox (developer edition)
  pacman:
    name: firefox-developer-edition
    state: present
  become: yes

- name: thunderbird
  pacman:
    name: thunderbird
    state: present
  become: yes

- name: kitty terminal
  pacman:
    name: kitty
    state: present
  become: yes

- name: thunar file manager
  pacman:
    name: thunar
    state: present
  become: yes

- name: file-roller archiver
  pacman:
    name: file-roller,lrzip,p7zip,unace,unrar
    state: present
  become: yes

- name: arandr
  pacman:
    name: arandr
    state: present
  become: yes

- name: arandr
  pacman:
    name: arandr
    state: present
  become: yes

- name: owncloud-client
  pacman:
    name: owncloud-client
    state: present
  become: yes

- name: vlc
  pacman:
    name: vlc
    state: present
  become: yes


- name: network-manager-applet
  pacman:
    name: network-manager-applet
    state: present
  become: yes

- name: keepassxc
  pacman:
    name: keepassxc
    state: present
  become: yes
