---
- name: Restart audiobookshelf containers
  become: true
  become_user: "{{ audiobookshelf_user }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    scope: user
  loop:
    - audiobookshelf.service
    - audiobookshelf-pod.service
