- name: create postgres container
  docker_container:
    name: bitwarden_db
    image: "postgres:latest"
    pull: yes
    env:
      POSTGRES_USER: "{{ bitwarden_db_user }}"
      POSTGRES_PASSWORD: "{{ bitwarden_db_password }}"
      POSTGRES_DB: "{{ bitwarden_db_name }}"
    volumes:
      - "/srv/containers/bitwarden_db/data:/var/lib/postgresql/data"
    networks:
      - name: containers
    restart_policy: "unless-stopped"

- name: create bitwarden_rs container
  docker_container:
    name: bitwarden
    image: "bitwardenrs/server-postgresql:latest"
    pull: yes
    env:
      ADMIN_TOKEN: "{{ bitwarden_admin_token }}"
      DATABASE_URL: "postgresql://{{ bitwarden_db_user }}:{{ bitwarden_db_password }}@bitwarden_db/{{ bitwarden_db_name }}"
      SIGNUPS_ALLOWED: "true"
      DOMAIN: "https://bitwarden.fkoehler.xyz"
    labels:
      traefik.http.routers.bitwarden.rule: "Host(`bitwarden.fkoehler.xyz`)"
      traefik.http.routers.bitwarden.tls: "true"
      traefik.http.routers.bitwarden.tls.certresolver: "letsencrypt"
      traefik.http.routers.bitwarden.middlewares: "customHeaders"
    volumes:
      - "/srv/containers/bitwarden:/data"
    networks:
      - name: containers
    restart_policy: "unless-stopped"
