# - name: create Firefox Sync postgresql user
#   postgresql_user:
#     name: "{{ postgres_user_firefoxsync }}"
#     password: "{{ postgres_password_firefoxsync }}"
#     login_user: "{{ postgres_user_root }}"
#     login_password: "{{ postgres_password_root }}"
#     login_host: "127.0.0.1"

# - name: create Firefox Sync database
#   postgresql_db:
#     name: "{{ postgres_db_firefoxsync }}"
#     owner: "{{ postgres_user_firefoxsync }}"
#     encoding: UTF-8
#     login_user: "{{ postgres_user_root }}"
#     login_password: "{{ postgres_password_root }}"
#     login_host: "127.0.0.1"
#

- name: create Firefox Sync data dir
  file:
    path: /srv/containers/firefoxsync
    state: directory
    owner: "1001"
    group: "1001"
    recurse: yes
    mode: "700"

- name: create Firefox Sync database
  postgresql_db:
    name: "{{ postgres_db_firefoxsync }}"
    state: absent
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create Firefox Sync postgresql user
  postgresql_user:
    name: "{{ postgres_user_firefoxsync }}"
    state: absent
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create Firefox Sync docker container
  docker_container:
    name: firefoxsync
    image: "mozilla/syncserver:latest"
    pull: yes
    container_default_behavior: no_defaults
    network_mode: default
    env:
      SYNCSERVER_PUBLIC_URL: "https://firefox.fkoehler.xyz"
      SYNCSERVER_SECRET: "{{ firefoxsync_secret_key }}"
      # SYNCSERVER_SQLURI: "postgresql://{{ postgres_user_firefoxsync }}:{{ postgres_password_firefoxsync }}@postgres/{{ postgres_db_firefoxsync }}"
      SYNCSERVER_SQLURI: "sqlite:////data/syncserver.db"
      SYNCSERVER_BATCH_UPLOAD_ENABLED: "true"
      SYNCSERVER_FORCE_WSGI_ENVIRON: "true"
    labels:
      traefik.http.routers.firefox.rule: "Host(`firefox.fkoehler.xyz`)"
      traefik.http.routers.firefox.tls: "true"
      traefik.http.routers.firefox.tls.certresolver: "letsencrypt"
      traefik.http.routers.firefox.middlewares: "customHeaders"
    volumes:
      - "/srv/containers/firefoxsync:/data"
    ports:
      - "5000:5000"
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"
