- name: install certbot
  package:
    name: certbot

- name: copy docker-compose files
  copy:
    src: docker-compose-files
    dest: "~"
    follow: yes
  notify: restart containers

- name: symlink private key
  file:
    path: "~/docker-compose-files/vps/cert.key"
    src: "/etc/letsencrypt/live/fkoehler.xyz/privkey.pem"
    state: link

- name: symlink certificate
  file:
    path: "~/docker-compose-files/vps/cert.pem"
    src: "/etc/letsencrypt/live/fkoehler.xyz/fullchain.pem"
    state: link

- name: symlink chain (OCSP stapling)
  file:
    path: "~/docker-compose-files/vps/chain.pem"
    src: "/etc/letsencrypt/live/fkoehler.xyz/chain.pem"
    state: link

- name: generate env file for vps
  ansible.builtin.template:
    src: .env.j2
    dest: "~/docker-compose-files/vps/.env"

- name: create/start containers
  community.docker.docker_compose:
    project_src: "~/docker-compose-files/vps"
    pull: yes

- name: flush handlers
  meta: flush_handlers
# - name: delete env files
#   file:
#     path: "~/docker-compose-files/vps/.env"
#     state: absent
