---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_distribution | lower }}.yml"
        - "install-{{ ansible_os_family | lower }}.yml"
        - "install-{{ ansible_system | lower }}.yml"
        - "install-fallback.yml"

- name: "Flatpak | Install flatpaks"
  when: ansible_system == 'Linux'
  become: true
  community.general.flatpak:
    method: system
    name:
      - com.super_productivity.SuperProductivity
      - net.werwolv.ImHex
      - org.fkoehler.KTailctl
      - org.telegram.desktop
