- name: restart containers
  community.docker.docker_compose:
    project_src: "~/docker-compose-files/vps"
    restarted: yes

- name: nextcloud add missing indicies
  ansible.builtin.command: docker exec -it --user www-data nextcloud php occ db:add-missing-indices

- name: nextcloud convert file cache
  ansible.builtin.command: docker exec -it --user www-data nextcloud php occ db:convert-filecache-bigint --no-interaction

- name: run mkinitcpio
  ansible.builtin.command: mkinitcpio -P

- name: update grub config
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg

- name: systemd reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart nginx
  community.docker.docker_compose:
    restarted: yes
    services: nginx_app
    project_src: "~/docker-compose-files/vps"

- name: restart nginx (blog)
  community.docker.docker_compose:
    restarted: yes
    services: nginx_app
    project_src: "~/docker-compose-files/blog"
