- name: create a data directory for anki sync server
  file:
    path: /srv/anki
    state: directory

- name: obtain docker-compose.yml for anki sync server
  git:
    accept_hostkey: yes
    repo: https://github.com/f-koehler/docker-anki-sync-server.git
    dest: ~/code/anki-server
  register: anki_sync_server_source

- name: remove anki sync server
  docker_compose:
    project_src: ~/code/anki-server
    state: absent
    remove_images: all
  when: anki_sync_server_source.changed

- name: start anki sync server
  docker_compose:
    project_src: ~/code/anki-server
    state: present
