- name: create radicale config dir
  file:
    path: /srv/radicale/config
    state: directory
    recurse: yes

- name: create radicale data dir
  file:
    path: /srv/radicale/data
    state: directory
    recurse: yes

- name: copy radicale config
  copy:
    src: config
    dest: /srv/radicale/config
  register: radicale_config

- name: obtain radicale source
  git:
    accept_hostkey: yes
    repo: https://github.com/Kozea/Radicale.git
    dest: ~/code/radicale
  register: radicale_source

- name: install radicale
  docker_compose:
    project_name: radicale
    definition:
      version: "3"
      services:
        server:
          build: ~/code/radicale/
          ports:
            - "5232:5232"
          volumes:
            - "/srv/radicale/data:/var/lib/radicale"
            - "/srv/radicale/config:/etc/config"
          deploy:
            restart_policy:
              condition: any
              max_attempts: 2
              delay: 5s
              window: 120s
