# Copyright © 2015 Fabian Köhler <fkoehler1024@googlemail.co

- name: Get tarball
  get_url:
      url=http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
      dest=/tmp/tl.tar.gz

- name: Make installer dir
  file: path=/tmp/tl state=directory

- name: Extract installer
  shell: tar -xzf /tmp/tl.tar.gz --strip-components=1 -C /tmp/tl

- name: Copy profile
  copy:
      src=texlive.profile
      dest=/tmp/tl/texlive.profile

- name: Install
  shell: cd /tmp/tl && ./install-tl -profile /tmp/tl/texlive.profile

- name: Remove installer dir
  file: path=/tmp/tl/ state=absent

- name: Remove tarball
  file: path=/tmp/tl.tar.gz state=absent
