- name: Install NetworkManager
  pacman:
    name: networkmanager networkmanager-openvpn networkmanager-vpnc network-manager-applet
    state: present
  become: yes

- name: Enable NetworkManager
  service:
    name: NetworkManager
    enabled: yes
  become: yes
