- hosts: 192.168.178.35
  remote_user: fkoehler
  tasks:
    - name: set hostname
      hostname: name=mars
      become: yes
    - name: set timezone
      timezone: name=Europe/Berlin
      become: yes
    - name: configure keymap of linux console
      copy: src=vconsole.conf dest=/etc/vconsole.conf
      become: yes
    - name: configure mirrors
      copy: src=mirrorlist dest=/etc/pacman.d/mirrorlist
      become: yes

    # microcode updates
    - name: ensure that the microcode package is installed
      pacman: name=intel-ucode state=present
      become: yes
      notify:
        - regenerate grub

    # haveged
    - name: ensure haveged is installed
      pacman: name=haveged state=present
      become: yes
      notify:
        - restart haveged
    - name: ensure that haveged is enabled
      service: name=haveged enabled=yes state=started
      become: yes

    # NTP
    - name: ensure that ntp is installed
      pacman: name=ntp state=present
      become: yes
    - name: ensure that ntpd is enabled
      service: name=ntpd enabled=yes state=started
      become: yes
      notify:
        - restart ntpd
    - name: ensure that ntp config is present
      copy: src=ntp.conf dest=/etc/ntp.conf
      become: yes
      notify:
        - restart ntpd

    # netdata
    - name: install netdata
      pacman: name=netdata state=present
      become: yes
      notify:
        - restart netdata
    - name: start netdata
      service: name=netdata enabled=yes state=started
      become: yes

    # version control systems
    - name: install version control systems
      pacman: name=git,mercurial,subversion
      become: yes

    # clang
    - name: install clang
      pacman: name=clang,llvm
      become: yes

    # install intel driver
    - name: install intel graphics driver
      pacman: name=mesa,xf86-video-intel,vulkan-intel state=present
      become: yes

    # i3
    - name: install i3
      pacman: name=i3-gaps,i3lock,i3status,dmenu,rofi state=present
      become: yes

    # install kitty terminal emulator
    - name: install kitty
      pacman: name=kitty state=present
      become: yes

    # login manager
    - name: install login manager
      pacman: name=sddm state=present
      become: yes
      notify:
        - restart login manager
    - name: enable login manager
      service: name=sddm enabled=yes state=started
      become: yes

    # software
    - name: install thunar
      pacman: name=thunar state=present
      become: yes

    - name: install file-roller
      pacman: name=file-roller,unzip,zip,lrzip,p7zip,unace,unrar state=present
      become: yes

    - name: install evince
      pacman: name=evince state=present
      become: yes

    - name: install nm-applet
      pacman: name=network-manager-applet state=present
      become: yes

    - name: install firefox
      pacman: name=firefox state=present
      become: yes

    - name: install thunderbird
      pacman: name=thunderbird state=present
      become: yes

    - name: install owncloud client
      pacman: name=owncloud-client state=present
      become: yes

    - name: install vlc
      pacman: name=vlc state=present
      become: yes

    - name: install emacs
      pacman: name=emacs state=present
      become: yes

    - name: install libre office
      pacman: name=libreoffice-fresh state=present
      become: yes

    # docker
    - name: install docker
      pacman: name=docker state=present
      become: yes
      notify:
        - restart docker
    - name: start docker
      service: name=docker enabled=yes state=started
      become: yes
    - name: add user to docker group
      user: name=fkoehler append=yes groups=docker
      become: yes

    # eduroam
    - name: create certificate directory
      file: dest=.certs state=directory
    - name: download telekom certificate
      get_url:
        url: https://www.rrz.uni-hamburg.de/services/sicherheit/pki/uhh-ca-daten/g-rootcert.crt
        dest: .certs/DeutscheTelekomRootCA2.crt
        checksum: sha256:b6191a50d0c3977f7da99bcdaac86a227daeb9679ec70ba3b0c9d92271c170d3

    # install fzf
    - name: obtain fzf
      git:
        clone: yes
        update: yes
        repo: https://github.com/junegunn/fzf.git
        accept_hostkey: yes
        dest: ~/.fzf
      notify:
        - install fzf

    - name: install gitconfig
      copy: src=.gitconfig dest=.gitconfig

    # zsh components
    - name: mkdir .zsh directory
      file: dest=.zsh state=directory
    - name: obtain oh-my-zsh
      git:
        clone: yes
        update: yes
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        accept_hostkey: yes
        dest: ~/.zsh/oh-my-zsh
    - name: obtain zsh-autosuggestions
      git:
        clone: yes
        update: yes
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        accept_hostkey: yes
        dest: ~/.zsh/zsh-autosuggestions
    - name: obtain zsh-completions
      git:
        clone: yes
        update: yes
        repo: https://github.com/zsh-users/zsh-completions.git
        accept_hostkey: yes
        dest: ~/.zsh/zsh-completions
    - name: obtain zsh-syntax-highlighting
      git:
        clone: yes
        update: yes
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        accept_hostkey: yes
        dest: ~/.zsh/zsh-syntax-highlighting
    - name: obtain z
      git:
        clone: yes
        update: yes
        repo: https://github.com/rupa/z.git
        accept_hostkey: yes
        dest: ~/.zsh/z

  handlers:
    - name: regenerate grub
      command: grub-mkconfig -o /boot/grub/grub.cfg
      become: yes
    - name: restart haveged
      service: name=haveged state=restarted
      become: yes
    - name: restart ntpd
      service: name=ntpd state=restarted
      become: yes
    - name: restart netdata
      service: name=netdata state=restarted
      become: yes
    - name: restart login manager
      service: name=sddm state=restarted
      become: yes
    - name: restart docker
      service: name=docker state=restarted
      become: yes
    - name: install fzf
      command: ~/.fzf/install --bin --64
