---
- name: Clone catppuccin modules in parallel
  ansible.builtin.git:
    repo: "https://github.com/catppuccin/{{ repo_name }}"
    dest: "{{ catppuccin_clone_path }}/{{ repo_name }}"
    version: main
    accept_hostkey: true
  loop_control:
    loop_var: repo_name
  loop:
    - bat
    - btop
    - eza
    - fzf
    - i3
    - lazygit
    - rofi
    - swaylock
    - yazi
    - zathura
    - zsh-syntax-highlighting
  async: 600
  poll: 0
  register: catppuccin_async_results
  changed_when: false

- name: Wait for all catppuccin git clones to finish
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: catppuccin_async_status
  until: catppuccin_async_status.finished
  retries: 120
  delay: 1
  loop: "{{ catppuccin_async_results.results }}"
  changed_when: item.result is defined and item.result.changed | default(false)
