---
- name: Clone catppuccin modules
  ansible.builtin.git: # TODO(fk): run in parallel
    repo: "https://github.com/catppuccin/{{ repo_name }}"
    dest: "{{ catppuccin_clone_path }}/{{ repo_name }}"
    version: main
    accept_hostkey: true
  loop_control:
    loop_var: repo_name
  loop:
    - alacritty
    - bat
    - btop
    - eza
    - fish
    - fzf
    - i3
    - lazygit
    - mako
    - rofi
    - swaylock
    - tmux
    - yazi
    - zathura
    - zsh-syntax-highlighting
- name: Set theme variables
  ansible.builtin.set_fact:
    alacritty_theme_path: >
      {{ catppuccin_clone_path }}/alacritty/catppuccin-{{ catppuccin_flavor | lower }}.toml
    bat_theme_path: >
      {{ catppuccin_clone_path }}/bat/themes/Cattppuccin {{ catppuccin_flavor }}.tmTheme
    lazygit_theme_path: >
      {{ catppuccin_clone_path }}/lazygit/themes/{{ catppuccin_flavor | lower }}/{{ catppuccin_accent | lower }}.yml
