---
- name: Clone catppuccin modules
  ansible.builtin.git:
    repo: https://github.com/catppuccin/{{ repo_name }}
    dest: ~/.local/share/catppuccin/{{ repo_name }}
    version: main
    accept_hostkey: true
  async: 300
  poll: 1
  loop_control:
    loop_var: repo_name
  loop:
    - alacritty
    - bat
    - btop
    - fish
    - fzf
    - i3
    - lazygit
    - mako
    - swaylock
    - tmux
    - yazi
    - zathura
    - zsh-syntax-highlighting
