---
- name: "Pacman | Install CUDA development tools"
  become: true
  community.general.pacman:
    state: present
    name:
      - base-devel
      - cuda
      - cuda-tools
      - cudnn
      - cudss

- name: "Pacman | Install HIP/ROCm development tools"
  become: true
  community.general.pacman:
    state: present
    name:
      - rocthrust
      - hipblas
      - hipblaslt
      - hipcub
      - hipsolver
      - hipsparse
      - hip-runtime-nvidia
      - hip-runtime-amd

- name: "Pacman | Install OpenCL development tools"
  become: true
  community.general.pacman:
    state: present
    name:
      - opencl-headers
      - ocl-icd
