- name: add goaccess GPG key
  apt_key:
    url: https://deb.goaccess.io/gnugpg.key
    state: present
  become: yes

- name: add goaccess apt repository
  apt_repository:
    repo: deb https://deb.goaccess.io/ bionic main
    state: present
  become: yes

- name: install goaccess
  apt:
    name: goaccess
    state: present
  become: yes

- name: install GeoIP database
  apt:
    name: geoip-database
    state: present
  become: yes

- name: create output directory
  file:
    path: /var/www/goaccess
    state: directory
    owner: www-data
    group: www-data
  become: yes

- name: copy systemd unit
  copy:
    src: goaccess-nginx@.service
    dest: /etc/systemd/system/goaccess-nginx@.service
  become: yes
  notify: systemd reload daemon

- name: copy nginx config
  copy:
    src: goaccess.conf
    dest: /etc/nginx/sites-available/goaccess.conf
  notify: restart nginx
  become: yes

- name: enable goaccess vserver
  file:
    src: /etc/nginx/sites-available/goaccess.conf
    path: /etc/nginx/sites-enabled/goaccess.conf
    state: link
  notify: restart nginx
  become: yes
