- name: create heimdall config dir
  file:
    path: /srv/heimdall/config
    recurse: yes
    state: directory

- name: install heimdall
  docker_container:
    name: "heimdall"
    image: linuxserver/heimdall
    env:
      TZ: "Europe/Berlin"
    volumes:
      - "/srv/heimdall/config:/config"
    ports:
      - "1337:80"
    restart_policy: "unless-stopped"
