---
- name: Generate SSH key
  community.crypto.openssh_keypair:
    # TODO(fk): parametrize with hostname & domain
    comment: "{{ username }}@destkop.corgi-dojo.ts.net"
    group: "{{ groupname }}"
    owner: "{{ username }}"
    mode: "400"
    path: "~/.ssh/id_ed25519"
    type: ed25519
