---
- name: Create SSH directory
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0700"

- name: Generate SSH key
  community.crypto.openssh_keypair:
    comment: "{{ username }}@{{ hostname }}.{{ domain }}"
    group: "{{ groupname }}"
    owner: "{{ username }}"
    mode: "400"
    path: "~/.ssh/id_ed25519"
    type: ed25519
