- name: create spack group
  group:
    name: spack
    state: present
    system: yes
  become: yes

- name: create spack user
  user:
    create_home: no
    group: spack
    hidden: yes
    name: spack
    state: present
    system: yes
  become: yes

- name: download spack
  git:
    accept_hostkey: yes
    clone: yes
    dest: /opt/spack
    repo: https://github.com/spack/spack.git
  become: yes

- name: set ownership of spack
  file:
    dest: /opt/spack
    mode: "u=rwX,g=rX,o=rX"
    owner: spack
    group: spack
    recurse: yes
  become: yes
