---
- name: Restart navidrome containers
  become: true
  become_user: "{{ navidrome_user }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    scope: user
  loop:
    - navidrome.service
    - navidrome-pod.service
    - tailscale.service
