- name: install cifs utils
  package:
    name: cifs-utils
    state: present

- name: create mount point
  file:
    path: /stash
    state: directory
    mode: "700"

- name: create credentials folder
  file:
    path: /etc/samba/credentials/
    mode: "700"
    state: directory

- name: create credentials file
  template:
    src: credentials
    dest: /etc/samba/credentials/stash
    mode: "600"

- name: create mount
  template:
    src: mount.mount
    dest: /etc/systemd/system/stash.mount
    mode: "600"
  notify: created_mount
# - name: install transmission
#   docker_container:
#     name: transmission
#     image: "haugene/transmission-openvpn:latest"
#     pull: yes
#     container_default_behavior: no_defaults
#     network_mode: default
#     ports:
#       - "9091:9091"
#     env:
#       USER: "{{ transmission_user }}"
#       PASS: "{{ transmission_password }}"
#     volumes:
#       - "/etc/timezone:/etc/timezone:ro"
#       - "/etc/localtime:/etc/localtime:ro"
#     restart_policy: "unless-stopped"
#     networks_cli_compatible: yes
