---
- name: Install nvidia GPU driver
  become: true
  community.general.pacman:
    name:
      - nvidia-open
      - nvidia-utils
      - lib32-nvidia-utils
    state: present

- name: Create pacman hook dir
  become: true
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop_control:
    loop_var: directory
  loop:
    - /etc/pacman.d/
    - /etc/pacman.d/hooks

- name: Setup nvidia pacman hook
  become: true
  ansible.builtin.copy:
    src: nvidia.hook
    dest: /etc/pacman.d/hooks/nvidia.hook
    owner: root
    group: root
    mode: "0644"
