---
- name: Restart tinymediamanager containers
  become: true
  become_user: "{{ tinymediamanager_user }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    scope: user
  loop:
    - tinymediamanager.service
    - tinymediamanager-pod.service
