- name: install iptables-persistent
  package:
    name: iptables-persistent
    state: present

- name: enable ipv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes

- name: create script to setup iptables rules
  template:
    src: port_forwarding.sh.j2
    dest: /root/port_forwarding.sh
    owner: root
    group: root
    mode: "0700"
  notify: reload_port_forwarding

- name: create systemd unit
  copy:
    src: port_forwarding.service
    dest: /etc/systemd/system/port_forwarding.service
    owner: root
    group: root
    mode: "0644"
  notify: reload_port_forwarding

- name: flush handlers
  meta: flush_handlers

- name: start port forwarding
  systemd:
    name: port_forwarding.service
    state: started
    enabled: yes
