---
- name: Restart paperless containers
  become: true
  become_user: "{{ paperless_user }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    scope: user
  loop:
    - paperless.service
    - broker.service
    - tika.service
    - gotenberg.service
    - paperless-pod.service
