---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_os_family | lower }}.yml"
        - "install-fallback.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Load theme tasks
  ansible.builtin.include_tasks: "theme-{{ fzf_theme }}.yml"

- name: Register fzf hooks
  ansible.builtin.set_fact:
    bash_hooks: "{{ (bash_hooks | default([])) + [fzf_hook_bash] }}" # noqa: var-naming[no-role-prefix]
    fish_hooks: "{{ (fish_hooks | default([])) + [fzf_hook_fish] }}" # noqa: var-naming[no-role-prefix]
    zsh_hooks: "{{ (zsh_hooks | default([])) + [fzf_hook_zsh] }}" # noqa: var-naming[no-role-prefix]
