- name: install diyhue container
  docker_container:
    name: "diyhue"
    image: "diyhue/core:latest"
    pull: yes
    restart_policy: "unless-stopped"
    volumes:
      - "/docker/diyhue/export:/opt/hue-emulator/export"
    env:
      MAC: "{{ diyhue_mac }}"
      IP: "{{ diyhue_ip }}"
    ports:
      - "8080:80/tcp"
      - "1900:1900/udp"
      - "2100:2100/udp"
      - "1982:1982/udp"
    network_mode: "bridge"
