---
tailscale_serve_quadlet_service_name: ""
tailscale_serve_quadlet_user: "{{ tailscale_serve_quadlet_service_name }}"
tailscale_serve_quadlet_group: "{{ tailscale_serve_quadlet_user }}"
tailscale_serve_quadlet_home: "/home/{{ tailscale_serve_quadlet_user }}"
tailscale_serve_quadlet_state_volume: "{{ tailscale_serve_quadlet_home }}/tailscale"
tailscale_serve_quadlet_pod_name: "{{ tailscale_serve_quadlet_service_name }}"
tailscale_serve_quadlet_hostname: "{{ tailscale_serve_quadlet_service_name }}"
tailscale_serve_quadlet_service_port: ""
tailscale_serve_quadlet_tags:
  - tag:container
