---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_os_family | lower }}.yml"
        - "install-fallback.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Create git config dir
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ groupname }}"
  loop_control:
    loop_var: directory
  loop:
    - ~/.config
    - ~/.config/git

- name: Configure git
  ansible.builtin.template:
    src: config.j2
    dest: ~/.config/git/config
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0644"

- name: Configure mergiraf languages
  ansible.builtin.shell: mergiraf languages --gitattributes > ~/.config/git/attributes
  args:
    creates: ~/.config/git/attributes
