---
- name: Load homebrew variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: Install homebrew dependencies
  become: true
  ansible.builtin.package:
    name: "{{ homebrew_dependencies }}"
    state: present

- name: Check if homebrew already installed
  ansible.builtin.stat:
    path: "{{ homebrew_root }}/bin/brew"
  register: homebrew_stat

- name: Install homebrew
  when: not homebrew_stat.stat.exists
  block:
    - name: Create homebrew directory
      ansible.builtin.file:
        path: "{{ homebrew_root }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ groupname }}"
        mode: "0755"

    - name: Install homebrew
      ansible.builtin.shell: |
        curl -fsSL https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C {{ homebrew_root }}

