- name: install pip
  pacman:
    name: python-pip
    state: present
  become: yes

- name: install docker-py
  pip:
    name: docker-py
    state: present
  become: yes

- name: run portainer container
  docker_container:
    name: portainer
    image: "portainer/portainer"
    state: started
    detach: true
    published_ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  become: yes
