# Copyright © 2015 Fabian Köhler <fkoehler1024@googlemail.com>

- name: Copy pacman.conf
  when: ansible_distribution == 'Archlinux'
  copy:
      src: pacman.conf
      dest: /etc/pacman.conf
      mode: 644

- name: Install ntp on Arch linux
  when: ansible_distribution == 'Archlinux'
  pacman: name=reflector state=installed

- name: Copy reflector.service
  when: ansible_distribution == 'Archlinux'
  copy:
      src: reflector.service
      dest: /etc/systemd/system/reflector.service
      mode: 644

- name: Copy reflector.timer
  when: ansible_distribution == 'Archlinux'
  copy:
      src: reflector.timer
      dest: /etc/systemd/system/reflector.timer
      mode: 644

- name: Start and enable reflector
  when: ansible_distribution == 'Archlinux'
  service:
      name: reflector.timer
      state: started
      enabled: yes
