- name: install git
  package:
    name: git

- name: obtain openvpn-install script
  git:
    accept_hostkey: yes
    repo: https://github.com/angristan/openvpn-install.git
    dest: ~/openvpn-install
  become: yes
  become_user: fkoehler

- name: install openvpn server
  command: /home/fkoehler/openvpn-install/openvpn-install.sh
  args:
    creates: /home/fkoehler/client.ovpn
  environment:
    AUTO_INSTALL: y 
