---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_distribution | lower }}.yml"
        - "install-{{ ansible_os_family | lower }}.yml"
        - "install-fallback.yml"
      paths:
        - "{{ role_path }}/tasks"
- name: Create tmux config dir
  ansible.builtin.file:
    path: ~/.config/tmux/plugins
    state: directory
    recurse: true
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0755"
- name: Configure tmux
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: "~/.config/tmux/tmux.conf"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0644"
