---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_distribution | lower }}.yml"
        - "install-{{ ansible_os_family | lower }}.yml"
        - "install-fallback.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Create tmux config dir
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ groupname }}"
  loop_control:
    loop_var: directory
  loop:
    - ~/.config
    - ~/.config/tmux
    - ~/.config/tmux/plugins

- name: Load theme tasks
  ansible.builtin.include_tasks: "theme-{{ tmux_theme }}.yml"

- name: Configure tmux
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: "~/.config/tmux/tmux.conf"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0644"
