- name: copy mkinitcpio.conf
  copy:
    src: mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
  become: yes
  notify:
    - run mkinitcpio

- name: install OVMF
  pacman:
    name: ovmf
    state: present
  become: yes

- name: use OVMF in qemu
  lineinfile:
    path: "/etc/libvirt/qemu.conf"
    line: "nvram = [ \"/usr/share/ovmf/x64/OVMF_CODE.fd:/usr/share/ovmf/x64/OVMF_VARS.fd\" ]"
    insertbefore: '^#nvram\s+=\s+\[\s*$'
  become: yes
  notify:
    - restart libvirtd
    - restart virtlogd

- name: configure kernel parameters
  copy:
    src: grub
    dest: /etc/default/grub
  become: yes
  notify: regenerate grub config
  register: pci_passthrough_restart_required

- name: set PCI passthrough devices
  copy:
    src: vfio.conf
    dest: /etc/modprobe.d/vfio.conf
  become: yes
  register: pci_passthrough_restart_required

- name: restart for PCI passthrough config
  shell: "sync && sleep 1 && reboot"
  become: yes
  when: pci_passthrough_restart_required
