- name: install lightdm
  pacman:
    name: lightdm
    state: present
  become: yes
  notify: restart lightdm

- name: install lightdm-gtk-greeter
  pacman:
    name: lightdm-gtk-greeter
    state: present
  become: yes
  notify: restart lightdm

- name: enable lightdm
  service:
    name: lightdm
    state: started
    enabled: yes
  become: yes
