- name: copy sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  become: yes
  notify:
    - restart sshd

- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: yes
