- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - certbot
    - certbot-dns-cloudflare

- name: create certbot config dir
  ansible.builtin.file:
    path: /etc/certbot
    owner: root
    group: root
    mode: 0700

- name: configure certbot cloudflare plugin
  ansible.builtin.template:
    src: cloudflare.ini
    dest: /etc/certbot/cloudflare.ini
    owner: root
    group: root
    mode: 0600

- name: run certbot
  ansible.builtin.command: >
    certbot
    certonly
    --expand
    --keep
    --non-interactive
    --agree-tos
    -m
    {{ letsencrypt_email }}
    --dns-cloudflare
    --dns-cloudflare-credentials
    /etc/certbot/cloudflare.ini
    -d {{domain}}
    {{subdomains|map('regex_replace', '^(.*)$', '-d \1\.'+domain)|join(' ')}}
  notify:
    - restart nginx
    - restart nginx (blog)

- name: copy systemd unit
  ansible.builtin.copy:
    src: "certbot.service"
    dest: "/etc/systemd/system/certbot.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_unit_copied

- name: copy systemd timer
  ansible.builtin.copy:
    src: "certbot.timer"
    dest: "/etc/systemd/system/certbot.timer"
    owner: root
    group: root
    mode: 0644
  register: systemd_timer_copied

- name: systemd reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_unit_copied or systemd_timer_copied

- name: enable systemd timers
  ansible.builtin.systemd:
    name: "certbot.timer"
    enabled: yes
    state: started
