- name: set up mail via ProtonMail
  block:
    - name: MX record
      community.general.cloudflare_dns:
        domain: fkoehler.xyz
        record: "@"
        type: MX
        state: present
        value: mail.protonmail.ch
        priority: 10
        account_api_key: "{{ cloudflare_api_key }}"
        account_email: "{{ cloudflare_email }}"
    - name: MX record 2
      community.general.cloudflare_dns:
        domain: fkoehler.xyz
        record: "@"
        type: MX
        state: present
        value: mailsec.protonmail.ch
        priority: 20
        account_api_key: "{{ cloudflare_api_key }}"
        account_email: "{{ cloudflare_email }}"
    - name: TXT records
      community.general.cloudflare_dns:
        domain: fkoehler.xyz
        record: "@"
        type: TXT
        state: present
        value: "{{ item }}"
        account_api_key: "{{ cloudflare_api_key }}"
        account_email: "{{ cloudflare_email }}"
      loop:
        - "google-site-verification=qfIZblxuEnl3V9LzTkjqaDyKY-kKbu3DW2uirfFgp4A"
        - "protonmail-verification=4ba64976c225cfcba3ba4364ce8d703a159d0604"
        - "v=spf1 include:_spf.protonmail.ch mx ~all"
    - name: CNAME record 1
      community.general.cloudflare_dns:
        domain: fkoehler.xyz
        record: "protonmail._domainkey"
        type: CNAME
        state: present
        value: "protonmail.domainkey.d6qobjpxh7q5uez3ilvagnjmekgvmblrx6k2l4kgfmn5m4jt6mikq.domains.proton.ch"
        account_api_key: "{{ cloudflare_api_key }}"
        account_email: "{{ cloudflare_email }}"
    - name: CNAME record 2
      community.general.cloudflare_dns:
        domain: fkoehler.xyz
        record: "protonmail2._domainkey"
        type: CNAME
        state: present
        value: "protonmail2.domainkey.d6qobjpxh7q5uez3ilvagnjmekgvmblrx6k2l4kgfmn5m4jt6mikq.domains.proton.ch"
        account_api_key: "{{ cloudflare_api_key }}"
        account_email: "{{ cloudflare_email }}"
    - name: CNAME record 3
      community.general.cloudflare_dns:
        domain: fkoehler.xyz
        record: "protonmail3._domainkey"
        type: CNAME
        state: present
        value: "protonmail3.domainkey.d6qobjpxh7q5uez3ilvagnjmekgvmblrx6k2l4kgfmn5m4jt6mikq.domains.proton.ch"
        account_api_key: "{{ cloudflare_api_key }}"
        account_email: "{{ cloudflare_email }}"
    - name: DMARC record
      community.general.cloudflare_dns:
        domain: fkoehler.xyz
        record: _dmarc
        type: TXT
        state: present
        value: "v=DMARC1; p=none"
        account_api_key: "{{ cloudflare_api_key }}"
        account_email: "{{ cloudflare_email }}"
- name: A records
  community.general.cloudflare_dns:
    domain: fkoehler.xyz
    record: "{{ item }}"
    type: A
    state: present
    value: "207.180.226.248"
    account_api_key: "{{ cloudflare_api_key }}"
    account_email: "{{ cloudflare_email }}"
  loop:
    - "@"
    - "goaccess"
    - "monica"
    - "nextcloud"
    - "pihole"
    - "www"
    - "xbrowsersync"
