- name: install hardened kernel
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - linux-hardened
    - linux-hardened-headers
    - linux-hardened-docs
  notify:
    - run mkinitcpio
    - update grub config

- name: remove unwanted kernels
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - linux-lts
    - linux-lts-headers
    - linux-lts-docs
    - linux
    - linux-headers
    - linux-docs
  notify:
    - run mkinitcpio
    - update grub config
