---
- name: Restart karakeep containers
  become: true
  become_user: "{{ karakeep_user }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    scope: user
  loop:
    - karakeep.service
    - karakeep-chrome.service
    - karakeep-meilisearch.service
