- name: copy ssh server config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "600"
  register: ssh_config

- name: restart ssh server
  systemd:
    name: sshd.service
    state: restarted
  when: ssh_config
