- name: install linux headers
  package:
    name: linux-headers

- name: install openafs including kernel modules
  aur:
    name: "{{ item }}"
  become_user: "{{ aur_user }}"
  loop:
    - openafs
    - openafs-modules-dkms
