- name: restart containers
  community.docker.docker_compose:
    project_src: "~/docker-compose-files/vps"
    restarted: yes

- name: nextcloud add missing indicies
  command: docker exec -it --user www-data nextcloud php occ db:add-missing-indices

- name: nextcloud convert file cache
  command: docker exec -it --user www-data nextcloud php occ db:convert-filecache-bigint --no-interaction
