---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_os_family }}.yml"
        - "install-fallback.yml"
      paths:
        - "{{ role_path }}/tasks"
- name: Add eza aliases
  ansible.builtin.set_fact: # noqa: var-naming[no-role-prefix]
    shell_aliases: >
      {{ (shell_aliases | default({})) | combine({
        'ls': 'eza --icons=never',
        'la': 'eza -a --icons=never',
        'll': 'eza -lg --icons=always',
        'lla': 'eza -lag --icons=always'
      }) }}
