- name: install docker packages
  package:
    name:
      - docker
      - docker-compose
      - python-docker

- name: enable docker service
  service:
    name: docker
    state: started
    enabled: yes
