- name: install docker packages
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
      - python-docker

- name: enable docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
