- name: get docker installation tasks
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}-{{ ansible_architecture|lower }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
