- name: remove old docker packages
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: install packages to add PPA
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: add docker PPA key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker PPA
  apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present