- name: remove old docker versions
  package:
    name: "{{ package }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
  loop_control:
    loop_var: package

- name: install packages to add PPA
  package:
    name: "{{ package }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  loop_control:
    loop_var: package

- name: add docker PPA key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker PPA
  apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: install docker
  package:
    name: "{{ package }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3
    - python3-docker
  loop_control:
    loop_var: package
