---
- name: Configure sway
  ansible.builtin.copy:
    src: sway
    dest: ~/.config/
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0644"
    directory_mode: "0755"

- name: Load theme tasks
  ansible.builtin.include_tasks:
    file: "theme-{{ sway_theme }}-sway.yml"
