---
- name: Create rofi configuration directory
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ groupname }}"
  loop_control:
    loop_var: directory
  loop:
    - ~/.config
    - ~/.config/rofi

- name: Load rofi theme tasks
  ansible.builtin.include_tasks: "theme-{{ sway_rofi_theme }}-rofi.yml"
