---
- name: Create rofi configuration directory
  ansible.builtin.file:
    path: "~/.config/rofi"
    state: directory
    mode: "0755"
    owner: "{{ username }}"
    group: "{{ groupname }}"
- name: Generate rofi config file
  ansible.builtin.template:
    src: rofi/config.rasi.j2
    dest: "~/.config/rofi/config.rasi"
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ groupname }}"
- name: Link rofi theme
  ansible.builtin.file:
    src: "{{ catppuccin_clone_path }}/rofi/themes/catppuccin-{{ catppuccin_flavor | lower }}.rasi"
    dest: "~/.config/rofi/theme.rasi"
    state: link
    mode: "0644"
    owner: "{{ username }}"
    group: "{{ groupname }}"
