---
- name: Start SwayOSD libinput backend
  become: true
  ansible.builtin.systemd_service:
    name: swayosd-libinput-backend.service
    state: started
    enabled: true

- name: Configure swayosd
  ansible.builtin.copy:
    src: "swayosd"
    dest: ~/.config/
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0644"
    directory_mode: "0755"
