http:
  routers:
    dashboard:
      rule: "Host(`fkoehler.xyz`)"
      service: api@internal
      entrypoints:
        - "dashboard"
      tls:
        options: modern
      middlewares:
        - "hsts-header"
        - "dashboard-auth"
    nextcloud:
      rule: "Host(`nextcloud.fkoehler.xyz`)"
      service: "nextcloud"
      entrypoints:
        - "https"
      tls:
        options: modern
      middlewares:
        - "hsts-header"
    nextcloud_http:
      rule: "Host(`nextcloud.fkoehler.xyz`)"
      service: "nextcloud"
      entrypoints:
        - "http"
      middlewares:
        - "redirect-to-https"
        - "hsts-header"
    git:
      rule: "Host(`git.fkoehler.xyz`)"
      service: "gitea"
      entrypoints:
        - "https"
      tls:
        options: modern
      middlewares:
        - "hsts-header"
    git_http:
      rule: "Host(`git.fkoehler.xyz`)"
      service: "gitea"
      entrypoints:
        - "http"
      middlewares:
        - "redirect-to-https"
        - "hsts-header"
  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "{{traefik_dashboard_auth}}"
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    hsts-header:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud:80/"
    gitea:
      loadBalancer:
        servers:
          - url: "http://gitea:3000/"
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/letsencrypt/live/fkoehler.xyz/fullchain.pem
        keyFile: /etc/letsencrypt/live/fkoehler.xyz/privkey.pem
  options:
    modern:
      minVersion: VersionTLS13
