---
- name: Install pipewire
  become: true
  community.general.pacman:
    name:
      - pipewire
      - wireplumber
      - wiremix
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - pipewire-audio
    state: present
