- file:
    path: /opt/nginx
    state: directory
  become: yes

- copy:
    src: nginx.conf
    dest: /opt/nginx/nginx.conf
  become: yes

- copy:
    src: mariadb.env
    dest: /tmp/mariadb.env

- copy:
    src: phpmyadmin.env
    dest: /tmp/phpmyadmin.env

- file:
    path: /opt/phpmyadmin
    state: directory
  become: yes

- copy:
    src: phpmyadmin_config.php
    dest: /opt/phpmyadmin/config.user.inc.php
  become: yes

- file:
    path: /etc/letsencrypt_nginx
    state: directory
  become: yes

- copy:
    src: /etc/letsencrypt/live/fkoehler.org/fullchain.pem
    dest: /etc/letsencrypt_nginx/fullchain.pem
    remote_src: yes
  become: yes

- copy:
    src: /etc/letsencrypt/live/fkoehler.org/privkey.pem
    dest: /etc/letsencrypt_nginx/privkey.pem
    remote_src: yes
  become: yes

- command: chown -R 101:101 /etc/letsencrypt_nginx
  args:
    warn: no
  become: yes

- command: chmod -R 700 /etc/letsencrypt_nginx
  args:
    warn: no
  become: yes

- docker_service:
    project_name: webserver
    restarted: yes
    definition:
      version: '3'
      services:
        mariadb:
          command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
          image: mariadb:latest
          env_file:
            - /tmp/mariadb.env
          restart: always
          volumes:
            - /opt/mariadb/:/var/lib/mysql
        phpmyadmin:
          depends_on:
            - mariadb
          image: phpmyadmin/phpmyadmin:latest
          env_file:
            - /tmp/phpmyadmin.env
          restart: always
          volumes:
            - /opt/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
        nextcloud:
          depends_on:
            - mariadb
            - redis
          image: nextcloud:stable-fpm
          restart: always
          volumes:
            - /opt/nextcloud:/var/www/html
        redis:
          image: redis:latest
          command: redis-server --appendonly yes
          restart: always
          volumes:
            - /opt/redis:/data
        proxy:
          depends_on:
            - nextcloud
          image: nginx:latest
          ports:
            - "80:80"
            - "443:443"
          restart: always
          volumes:
            - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/letsencrypt.conf:ro
            - /etc/letsencrypt_nginx:/etc/letsencrypt:ro
  become: yes

- file:
    path: /tmp/mariadb.env
    state: absent

- file:
    path: /tmp/phpmyadmin.env
    state: absent
