---
- name: "Snap | Install alacritty"
  become: true
  community.general.snap:
    name: alacritty
    state: present
    classic: true

- name: "Apt | Install Cascadia Code Nerd Font"
  become: true
  ansible.builtin.apt:
    name: fonts-cascadia-code
    state: present
