---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_os_family | lower }}.yml"
        - "install-fallback.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Create alacritty config dir
  ansible.builtin.file:
    path: ~/.config/alacritty
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0755"

- name: Load theme tasks
  ansible.builtin.include_tasks: "theme-{{ alacritty_theme }}.yml"

- name: Configure alacritty
  ansible.builtin.template:
    src: alacritty.toml.j2
    dest: ~/.config/alacritty/alacritty.toml
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0644"
