- name: install home-assistant container
  docker_container:
    name: "home-assistant"
    image: "homeassistant/{{ home_assistant_image }}"
    pull: yes
    restart_policy: "unless-stopped"
    volumes:
      - "/docker/home-assistant/:/config"
    env:
      TZ: "Europe/Berlin"
    network_mode: "host"
