---
- name: Create karakeep group
  become: true
  ansible.builtin.group:
    name: "{{ karakeep_group }}"

- name: Create karakeep user
  become: true
  ansible.builtin.user:
    name: "{{ karakeep_user }}"
    group: "{{ karakeep_group }}"
    state: present
    create_home: true
    home: "{{ karakeep_home }}"

- name: Enable linger for karakeep user
  become: true
  ansible.builtin.command:
    cmd: loginctl enable-linger "{{ karakeep_user }}"

- name: Create quadlet directory
  become: true
  become_user: "{{ karakeep_user }}"
  ansible.builtin.file:
    path: "{{ karakeep_home }}/.config/containers/systemd"
    state: directory
    owner: "{{ karakeep_user }}"
    group: "{{ karakeep_group }}"
    mode: 0755
    recurse: true

- name: Generate quadlet files
  become: true
  become_user: "{{ karakeep_user }}"
  notify: Restart karakeep containers
  register: quadlet_result
  ansible.builtin.template:
    src: "{{ template }}"
    dest: "{{ karakeep_home }}/.config/containers/systemd/{{ template }}"
    owner: "{{ karakeep_user }}"
    group: "{{ karakeep_group }}"
    mode: 0644
  loop_control:
    loop_var: template
  loop:
    - karakeep.container
    - karakeep.pod
    - karakeep.network

- name: Generate environment file
  become: true
  become_user: "{{ karakeep_user }}"
  notify: Restart karakeep containers
  register: env_result
  ansible.builtin.template:
    src: "karakeep.env"
    dest: "{{ karakeep_home }}/.env"
    owner: "{{ karakeep_user }}"
    group: "{{ karakeep_group }}"
    mode: 0600

- name: Reload systemd daemon
  become: true
  become_user: "{{ karakeep_user }}"
  when: quadlet_result.changed or env_result.changed
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Validate quadlet files
  become: true
  become_user: "{{ karakeep_user }}"
  changed_when: false
  ansible.builtin.command:
    cmd: /usr/lib/podman/quadlet -dryrun -user

- name: Create volumes
  become: true
  notify: Restart karakeep containers
  ansible.builtin.file:
    path: "{{ volume }}"
    state: directory
    owner: "{{ karakeep_user }}"
    group: "{{ karakeep_group }}"
    mode: 0700
  loop_control:
    loop_var: volume
  loop:
    - "{{ karakeep_volume_data }}"
    - "{{ karakeep_volume_meilisearch }}"

- name: Enable karakeep containers
  become: true
  become_user: "{{ karakeep_user }}"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  loop:
    - karakeep-chrome.service
    - karakeep-meilisearch.service
    - karakeep.service
