---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_os_family | lower }}.yml"
        - "install-fallback.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Create btop configuration directory
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0755
  loop_control:
    loop_var: directory
  loop:
    - "~/.config"
    - "~/.config/btop"
    - "~/.config/btop/themes"

- name: Load theme tasks
  ansible.builtin.include_tasks:
    file: "theme-{{ btop_theme }}.yml"
