- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - podman
    - buildah
    - fuse-overlayfs
    - btrfs-progs
    - catatonit
    - crun
    - slirp4netns

- name: set subuids/subgids
  ansible.builtin.template:
    dest: "/etc/{{ item }}"
    src: subids
    mode: 0644
  loop:
    - subuid
    - subgid
  notify: podman system migrate

- name: configure user namespaces
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.d/podman.conf

- ansible.builtin.meta: flush_handlers

- name: make podman users lingering
  ansible.builtin.command: "loginctl enable-linger {{ item }}"
  args:
    creates: "/var/lib/systemd/linger/{{ item }}"
  loop: "{{ podman_users }}"
