- name: create directories for gitea
  file:
    path: "/srv/containers/gitea"
    state: directory
    recurse: yes

- name: create Gitea postgresql user
  postgresql_user:
    name: "{{ postgres_user_gitea }}"
    password: "{{ postgres_password_gitea }}"
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create Gitea postgresql database
  postgresql_db:
    name: "{{ postgres_db_gitea }}"
    owner: "{{ postgres_user_gitea }}"
    encoding: UTF-8
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create Gitea container
  docker_container:
    name: gitea
    image: "gitea/gitea:latest"
    env:
      RUN_MODE: prod
      DOMAIN: git.fkoehler.xyz
      SSH_DOMAIN: git.fkoehler.xyz
      HTTP_PORT: "3000"
      ROOT_URL: "https://git.fkoehler.xyz"
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_NAME: "{{ postgres_db_gitea }}"
      DB_USER: "{{ postgres_user_gitea }}"
      DB_PASSWD: "{{ postgres_password_gitea }}"
      INSTALL_LOCK: "true"
      SECRET_KEY: "{{ gitea_secret_key }}"
      DISABLE_REGISTRATION: "true"
      SSH_LISTEN_PORT: "2222"
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - "/srv/containers/gitea:/data"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"

- name: enable Gitea site
  copy:
    src: site-gitea.conf
    dest:  /srv/containers/nginx/config/sites-enabled/gitea.conf
  notify:
    - restart nginx container

- name: create directory for SSH forwarding script
  file:
    path: /app/gitea
    state: directory
    recurse: yes

- name: copy Gitea SSH forwarding script
  copy:
    src: gitea-ssh-forward.sh
    dest: /app/gitea/gitea
    mode: "755"

- name: add git group
  group:
    name: git
    state: present

- name: add git user
  user:
    generate_ssh_key: yes
    group: git
    name: git
    ssh_key_type: ed25519
    home: /home/git
    move_home: yes
  register: git_user

- name: symlink git user authorized keys file
  file:
    src: /srv/containers/gitea/git/.ssh/authorized_keys
    dest: /home/git/.ssh/authorized_keys
    state: link

- name: authorized keys
  lineinfile:
    path: /srv/containers/gitea/git/.ssh/authorized_keys
    owner: git
    line: 'no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty {{ git_user["ssh_public_key"] }}'