- name: create directory for docker volumes
  file:
    state: directory
    recurse: yes
    path: /srv/containers

- include_tasks: nginx.yml
- include_tasks: postgres.yml
- include_tasks: nextcloud.yml
