- name: install the python postgres adapter
  package:
    name: python-psycopg2

- name: create docker network
  docker_network:
    name: containers

- name: create volume for postgres
  docker_volume:
    name: postgres_data

- name: create postgres container
  docker_container:
    name: postgres
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    env:
      POSTGRES_USER: "{{ postgres_user_root }}"
      POSTGRES_PASSWORD: "{{ postgres_password_root }}"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"

- name: wait for postgres to start
  shell: /usr/bin/pg_isready -U "{{ postgres_user_root }}" -h "127.0.0.1" -p 5432
  register: result
  until: result.rc == 0
  retries: 12
  delay: 10

- name: create nextcloud postgresql user
  postgresql_user:
    name: "{{ postgres_user_nextcloud }}"
    password: "{{ postgres_password_nextcloud }}"
    role_attr_flags: NOSUPERUSER
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create nextcloud database
  postgresql_db:
    name: "{{ postgres_db_nextcloud }}"
    owner: "{{ postgres_user_nextcloud }}"
    encoding: UTF-8
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create volumes for nextcloud
  docker_volume:
    name: "{{ item }}"
  loop:
    - nextcloud_apps
    - nextcloud_config
    - nextcloud_data

- name: create nextcloud container
  docker_container:
    name: nextcloud
    image: "nextcloud:latest"
    ports:
      - "8000:80"
    env:
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_user_admin }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_password_admin }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_trusted_domains }}"
      POSTGRES_DB: "{{ postgres_db_nextcloud }}"
      POSTGRES_USER: "{{ postgres_user_nextcloud }}"
      POSTGRES_PASSWORD: "{{ postgres_password_nextcloud }}"
      POSTGRES_HOST: "postgres"
    volumes:
      - "nextcloud_apps:/var/www/html/custom_apps"
      - "nextcloud_config:/var/www/html/config"
      - "nextcloud_data:/var/www/html/data"
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"

- name: create synapse postgresql user
  postgresql_user:
    name: "{{ postgres_user_synapse }}"
    password: "{{ postgres_password_synapse }}"
    role_attr_flags: NOSUPERUSER
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create synapse database
  postgresql_db:
    name: "{{ postgres_db_synapse }}"
    owner: "{{ postgres_user_synapse }}"
    encoding: UTF-8
    lc_collate: "C"
    lc_ctype: "C"
    template: "template0"
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create volumes for synapse
  docker_volume:
    name: "synapse_data"

- name: create synapse config
  template:
    src: "homeserver.yaml"
    dest: "/var/lib/docker/volumes/synapse_data/_data/homeserver.yaml"
    mode: "644"
    owner: "991"
    group: "991"
  notify: restart synapse container

- name: copy synapse log config
  copy:
    src: "synapse.log.config"
    dest: "/var/lib/docker/volumes/synapse_data/_data/{{ synapse_domain }}.log.config"
    mode: "644"
    owner: "991"
    group: "991"
  notify: restart synapse container

- name: set synapse signing key
  template:
    src: "synapse.signing.key"
    dest: "/var/lib/docker/volumes/synapse_data/_data/{{ synapse_domain }}.signing.key"
    mode: "644"
    owner: "991"
    group: "991"
  notify: restart synapse container

- name: create subdirectories for synapse
  file:
    path: "/var/lib/docker/volumes/synapse_data/_data/{{ item }}"
    state: directory
    owner: "991"
    group: "991"
  loop:
    - media_store
    - uploads
    - logs
  notify: restart synapse container

- name: create synapse container
  docker_container:
    name: synapse
    image: "matrixdotorg/synapse:latest"
    ports:
      - "18008:8008"
      - "18009:8009"
      - "18448:8448"
    volumes:
      - "synapse_data:/data"
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"
    env:
      SYNAPSE_SERVER_NAME: "{{ synapse_domain }}"
      SYNAPSE_REPORT_STATS: "no"
      UID: "991"
      GID: "991"

- name: install nginx
  package:
    name: nginx

- name: start/enable nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: install certbot
  package:
    name:
      - certbot
      - certbot-nginx

- name: open ports for nginx
  ufw:
    rule: allow
    port: "{{ item | int }}"
  loop:
    - 80
    - 443
    - 8448
