- name: create directories for nginx
  file:
    path: "/srv/containers/nginx/{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "config/sites-enabled"
    - "content/default"
    - "log"

- name: copy test html
  copy:
    src: index.html
    dest: /srv/containers/nginx/content/default/index.html

- name: create nginx container
  docker_container:
    name: nginx
    image: "nginx:alpine"
    pull: yes
    container_default_behavior: no_defaults
    network_mode: default
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - "/srv/containers/nginx/config:/etc/nginx/:ro"
      - "/etc/letsencrypt/:/etc/letsencrypt:ro"
      - "/srv/containers/nginx/content:/www:ro"
      - "/srv/containers/nextcloud:/var/www/html:ro"
      - "/srv/containers/nginx/log:/log"
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"

- name: generate Diffie-Hellman parameters
  command:
    cmd: openssl dhparam -out /srv/containers/nginx/config/dhparam.pem 4096
    creates: /srv/containers/nginx/config/dhparam.pem
  notify: restart nginx container

- name: copy nginx config files
  copy:
    src: "{{ item }}"
    dest: "/srv/containers/nginx/config/{{ item }}"
  loop:
    - mime.types
    - nginx.conf
    - proxy.conf
    - ssl.conf
  notify:
    - restart nginx container

- name: open ports for nginx
  ufw:
    rule: allow
    port: "{{ item | int }}"
  loop:
    - 80
    - 443
