- name: create directories for InfluxDB
  file:
    path: /srv/containers/influxdb/data
    state: directory
    recurse: yes

- name: install python module for InfluxDB
  package:
    name: python-influxdb
    state: "present"

- name: create InfluxDB container
  docker_container:
    name: influxdb
    image: "influxdb:latest"
    env:
      INFLUXDB_HTTP_AUTH_ENABLED: "TRUE"
      INFLUXDB_ADMIN_USER: "{{ influxdb_user_admin }}"
      INFLUXDB_ADMIN_PASSWORD: "{{ influxdb_password_admin }}"
    volumes:
      - "/srv/containers/influxdb/data:/var/lib/influxdb"
    ports:
      - "8086:8086"
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"

- name: create directories for Telegraf
  file:
    path: /srv/containers/telegraf/config
    state: directory
    recurse: yes

- name: create Telegraf InfluxDB DB
  influxdb_database:
    login_username: "{{ influxdb_user_admin }}"
    login_password: "{{ influxdb_password_admin }}"
    database_name: "{{ influxdb_db_telegraf }}"

- name: create Telegraf InfluxDB user
  influxdb_user:
    user_name: "{{ influxdb_user_telegraf }}"
    user_password: "{{ influxdb_password_telegraf }}"
    login_username: "{{ influxdb_user_admin }}"
    login_password: "{{ influxdb_password_admin }}"
    grants:
      - database: "{{ influxdb_db_telegraf }}"
        privilege: "ALL"

- name: copy Telegraf config
  copy:
    src: telegraf.conf
    dest: /srv/containers/telegraf/config/telegraf.conf
  notify:
    - restart Telegraf container

- name: create Telegraf container
  docker_container:
    name: telegraf
    image: "telegraf:latest"
    volumes:
      - "/srv/containers/telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"

- name: create Grafana InfluxDB user
  influxdb_user:
    user_name: "{{ influxdb_user_grafana }}"
    user_password: "{{ influxdb_password_grafana }}"
    login_username: "{{ influxdb_user_admin }}"
    login_password: "{{ influxdb_password_admin }}"
    grants:
      - database: "{{ influxdb_db_telegraf }}"
        privilege: "READ"

- name: create Grafana postgresql user
  postgresql_user:
    name: "{{ postgres_user_grafana }}"
    password: "{{ postgres_password_grafana }}"
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create Nextcloud database
  postgresql_db:
    name: "{{ postgres_db_grafana }}"
    owner: "{{ postgres_user_grafana }}"
    encoding: UTF-8
    login_user: "{{ postgres_user_root }}"
    login_password: "{{ postgres_password_root }}"
    login_host: "127.0.0.1"

- name: create directories for grafana
  file:
    path: "/srv/containers/grafana/{{ item }}"
    state: directory
    recurse: yes
    owner: "472"
  loop:
    - config
    - data
    - logs
    - plugins

- name: generate Grafana config
  template:
    src: grafana.ini
    dest: /srv/containers/grafana/config/grafana.ini
  notify:
    - restart Grafana container

- name: create Grafana container
  docker_container:
    name: grafana
    image: "grafana/grafana:latest"
    ports:
      "3000:3000"
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"
    volumes:
      - "/srv/containers/grafana/config:/etc/grafana"
      - "/srv/containers/grafana/data:/var/lib/grafana/"
      - "/srv/containers/grafana/logs:/var/log/grafana/"
      - "/srv/containers/grafana/plugins:/var/lib/grafana/plugins/"