- name: create directory for Traefik
  file:
    path: /srv/containers/traefik/
    state: directory
    recurse: yes

- name: create an empty acme.json
  file:
    path: /srv/containers/traefik/acme.json
    state: touch

- name: copy static Traefik config
  copy:
    src: traefik.toml
    dest: /srv/containers/traefik/traefik.toml
  notify:
    - restart Traefik container

- name: create Traefik container
  docker_container:
    name: traefik
    image: "traefik:latest"
    pull: yes
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      # - "0.0.0.0:8080:8080"
    volumes:
      - "/srv/containers/traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "/srv/containers/traefik/acme.json:/etc/traefik/acme.json:ro"
      - "/etc/letsencrypt/:/etc/letsencrypt:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --providers.docker
    networks:
      - name: containers
    networks_cli_compatible: yes
    restart_policy: "unless-stopped"

- name: open ports for Traefik
  ufw:
    rule: allow
    port: "{{ item | int }}"
  loop:
    - 80
    - 443
