---
- name: "Pacman | Install rust development tools"
  become: true
  notify:
    - Install rust toolchains
  community.general.pacman:
    state: present
    name:
      - base-devel
      - rustup
      - cargo
