- name: install cifs utils
  package:
    name: cifs-utils
    state: present

- name: create mount point
  file:
    path: /stash
    state: directory
    mode: "700"

- name: create credentials folder
  file:
    path: /etc/samba/credentials/
    mode: "700"
    state: directory

- name: create credentials file
  template:
    src: credentials
    dest: /etc/samba/credentials/stash
    mode: "600"

- name: create mount
  template:
    src: mount.mount
    dest: /etc/systemd/system/stash.mount
    mode: "600"
  notify: created_mount

- name: create automount
  copy:
    src: stash.automount
    dest: /etc/systemd/system/stash.automount
    mode: "600"
  notify: created_mount

- name: disable mount
  systemd:
    name: stash.automount
    state: stopped
    enabled: no

- name: enable automount
  systemd:
    name: stash.automount
    state: started
    enabled: yes

- name: docker network for download stack
  docker_network:
    name: download_stack

- name: install transmission
  docker_container:
    name: transmission
    image: "linuxserver/transmission:latest"
    pull: yes
    container_default_behavior: no_defaults
    network_mode: default
    ports:
      - "9091:9091"
      - "51413:51413"
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "Europe/Berlin"
      USER: "{{ transmission_user }}"
      PASS: "{{ transmission_password }}"
    volumes:
      - "/srv/containers/transmission/config:/config"
      - "/stash/transmission:/downloads"
    restart_policy: "unless-stopped"
    networks:
      - name: download_stack
    networks_cli_compatible: yes

- name: install jackett
  docker_container:
    name: jackett
    image: "linuxserver/jackett:latest"
    pull: yes
    container_default_behavior: no_defaults
    network_mode: default
    ports:
      - "9117:9117"
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "Europe/Berlin"
      AUTO_UPDATE: "true"
    volumes:
      - "/srv/containers/jackett/config:/config"
    restart_policy: "unless-stopped"
    networks:
      - name: download_stack
    networks_cli_compatible: yes

- name: install radarr
  docker_container:
    name: radarr
    image: "linuxserver/radarr:latest"
    pull: yes
    container_default_behavior: no_defaults
    network_mode: default
    ports:
      - "7878:7878"
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "Europe/Berlin"
    volumes:
      - "/srv/containers/radarr/config:/config"
      - "/stash/Media:/movies"
      - "/stash/transmission:/downloads"
    restart_policy: "unless-stopped"
    networks:
      - name: download_stack
    networks_cli_compatible: yes

- name: install sonarr
  docker_container:
    name: sonarr
    image: "linuxserver/sonarr:latest"
    pull: yes
    container_default_behavior: no_defaults
    network_mode: default
    ports:
      - "8989:8989"
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "Europe/Berlin"
    volumes:
      - "/srv/containers/sonarr/config:/config"
      - "/stash/Media:/tv"
      - "/stash/transmission:/downloads"
    restart_policy: "unless-stopped"
    networks:
      - name: download_stack
    networks_cli_compatible: yes

- name: install bazarr
  docker_container:
    name: bazarr
    image: "linuxserver/bazarr:latest"
    pull: yes
    container_default_behavior: no_defaults
    network_mode: default
    ports:
      - "6767:6767"
    env:
      PUID: "1001"
      PGID: "1001"
      TZ: "Europe/Berlin"
    volumes:
      - "/srv/containers/bazarr/config:/config"
      - "/stash/Media:/movies"
      - "/stash/Media:/tv"
      - "/stash/transmission:/downloads"
    restart_policy: "unless-stopped"
    networks:
      - name: download_stack
    networks_cli_compatible: yes
