---
homebrew_root: ~/.homebrew
homebrew_dependencies:
  archlinux:
    - base-devel
    - curl
    - file
    - git
    - procps-ng
  ubuntu:
    - build-essential
    - curl
    - file
    - git
    - procps
