---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_os_family | lower }}.yml"
        - "install-fallback.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Clone neovim config
  # TODO(fk): more fine-grained error handling, only accept if due to modified local clone
  failed_when: false
  ansible.builtin.git:
    repo: "git@github.com:f-koehler/neovim-config.git"
    dest: "~/.config/nvim"
    version: main
    accept_hostkey: true

- name: Set nvim as default editor
  ansible.builtin.set_fact: # noqa: var-naming[no-role-prefix]
    environment_variables: >
      {{ (environment_variables | default({})) | combine({
        'EDITOR': 'nvim',
        'VISUAL': 'nvim'
      }) }}
