- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - intel-media-driver
    - libva-intel-driver
    - libva-utils
    - libxcursor
    - libxinerama
    - libxrandr
    - libxss
    - libxtst
    - linux-firmware
    - mesa
    - vulkan-intel
    - vulkan-mesa-layers
    - xf86-video-intel

- name: install 32bit packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - lib32-mesa
    - lib32-vulkan-intel
    - lib32-vulkan-mesa-layers
  when: graphics_driver_32bit_support
