- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nvidia
    - nvidia-utils
    - nvidia-settings
    - opencl-nvidia
    - xorg-server-devel
    - libva-vdpau-driver
    - vdpauinfo

- name: install 32bit packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - lib32-nvidia-utils
    - lib32-opencl-nvidia
  when: graphics_driver_32bit_support
