---
- name: Load installation tasks
  ansible.builtin.include_tasks: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_os_family | lower }}.yml"
        - "install-fallback.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Add bat alias
  ansible.builtin.set_fact:
    shell_aliases: "{{ (shell_aliases | default({})) | combine({'cat': 'bat --style=plain --paging=never'}) }}" # noqa: var-naming[no-role-prefix]

- name: Make sure config dir exists
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0755"
    recurse: true
  loop_control:
    loop_var: directory
  loop:
    - ~/.config
    - ~/.config/bat
    - ~/.config/bat/themes

- name: Configure bat
  ansible.builtin.template:
    src: config.j2
    dest: "~/.config/bat/config"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "0644"
# TODO(fk): use bat for man pages for the full batman experience
