---
- name: Configure ssh-server
  become: true
  notify: Restart ssh-server
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"

- name: Enable ssh-server
  become: true
  ansible.builtin.service:
    name: "{{ ssh_server_service_name }}"
    enabled: true
    state: started
