---
- name: Install openssh
  community.general.pacman:
    name: openssh
    state: present
  become: true

- name: Set openssh service name
  ansible.builtin.set_fact:
    ssh_server_service_name: sshd
