- name: Install OpenSSH
  pacman:
    name: openssh
    state: present
  become: yes

- name: Enable OpenSSH server
  service:
    name: sshd.service
    state: started
    enabled: yes
  become: yes
