- name: install openssh
  pacman:
    name: openssh
    state: present
  become: yes
  notify:
    - copy sshd_config
    - restart sshd

- name: start/enable ssh server
  service:
    name: sshd
    state: started
    enabled: yes
  become: yes
