- name: install rust CLI tools
  package:
    name: "{{ item }}"
  loop:
    - bat
    - exa
    - fd
    - hyperfine
    - procs
    - ripgrep
    - sd
    - tokei

# TODO: add dust and bottom

- name: install tools
  package:
    name: "{{ item }}"
  loop:
    - wget
    - fzf
