- name: install wget
  pacman:
    name: wget
    state: present
  become: yes

- name: install htop
  pacman:
    name: htop
    state: present
  become: yes

- name: install bat
  pacman:
    name: bat
    state: present
  become: yes

- name: install ncdu
  pacman:
    name: ncdu
    state: present
  become: yes

- name: install fzf
  pacman:
    name: fzf
    state: present
  become: yes

- name: install zsh
  pacman:
    name: zsh
    state: present
  become: yes
